-- V51: financial_asset — one row per priceable asset (crypto, stock, ETF), replacing the
-- hardcoded ticker registries (CoinGeckoPriceProvider.TICKER_TO_ID and the drifted crypto
-- skip-list in YahooFinancePriceProvider). Aggregator references are dedicated nullable
-- columns — one column per aggregator (decided 2026-07-08 over a junction table: there is
-- exactly one external ref per (asset, aggregator)). A row is priceable on the aggregators
-- whose ref column is set; `status` tracks the resolution lifecycle:
--   PENDING   discovered but not linked to any aggregator yet (awaiting auto/user resolution)
--   AUTO      linked automatically (single or market-cap-dominant search match)
--   USER      linked or corrected by the operator
--   WORTHLESS delisted coin priced at a known zero (no aggregator ref)
-- `last_eur_value`/`price_synced_at` persist the latest known price so a restart doesn't start
-- from an empty in-memory cache. See FinancialAssetService for the resolution rules.
CREATE TABLE financial_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Uppercase internal ticker as seen in holdings and imports (BTC, IWDA.AS, …).
    symbol VARCHAR(30) NOT NULL,
    name VARCHAR(120),
    -- CRYPTO | STOCK | ETF | UNKNOWN — routing hint and UI grouping, not a hard constraint.
    type VARCHAR(10) NOT NULL DEFAULT 'UNKNOWN',
    status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    isin VARCHAR(12),
    -- CoinGecko coin id (e.g. 'bitcoin', 'matic-network'), used verbatim in API calls.
    coingecko_id VARCHAR(100),
    -- Yahoo Finance symbol (e.g. 'IWDA.AS', 'MC.PA'), used verbatim in API calls.
    yahoo_symbol VARCHAR(50),
    last_eur_value NUMERIC(20, 8),
    price_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_financial_asset_symbol UNIQUE (symbol)
);

-- Seed 1: the crypto mappings formerly hardcoded in CoinGeckoPriceProvider, with CoinGecko's
-- canonical coin names. Status AUTO — resolved by code, not confirmed by a user.
INSERT INTO financial_asset (symbol, name, type, status, coingecko_id) VALUES
    ('BTC',   'Bitcoin',       'CRYPTO', 'AUTO', 'bitcoin'),
    ('ETH',   'Ethereum',      'CRYPTO', 'AUTO', 'ethereum'),
    ('SOL',   'Solana',        'CRYPTO', 'AUTO', 'solana'),
    ('BNB',   'BNB',           'CRYPTO', 'AUTO', 'binancecoin'),
    ('ADA',   'Cardano',       'CRYPTO', 'AUTO', 'cardano'),
    ('XRP',   'XRP',           'CRYPTO', 'AUTO', 'ripple'),
    ('DOGE',  'Dogecoin',      'CRYPTO', 'AUTO', 'dogecoin'),
    ('DOT',   'Polkadot',      'CRYPTO', 'AUTO', 'polkadot'),
    ('MATIC', 'Polygon',       'CRYPTO', 'AUTO', 'matic-network'),
    ('AVAX',  'Avalanche',     'CRYPTO', 'AUTO', 'avalanche-2'),
    ('LINK',  'Chainlink',     'CRYPTO', 'AUTO', 'chainlink'),
    ('UNI',   'Uniswap',       'CRYPTO', 'AUTO', 'uniswap'),
    ('ATOM',  'Cosmos Hub',    'CRYPTO', 'AUTO', 'cosmos'),
    ('LTC',   'Litecoin',      'CRYPTO', 'AUTO', 'litecoin'),
    ('NEAR',  'NEAR Protocol', 'CRYPTO', 'AUTO', 'near'),
    ('ARB',   'Arbitrum',      'CRYPTO', 'AUTO', 'arbitrum'),
    ('OP',    'Optimism',      'CRYPTO', 'AUTO', 'optimism'),
    ('SHIB',  'Shiba Inu',     'CRYPTO', 'AUTO', 'shiba-inu'),
    ('PEPE',  'Pepe',          'CRYPTO', 'AUTO', 'pepe'),
    ('SUI',   'Sui',           'CRYPTO', 'AUTO', 'sui');

-- Seed 2: identity Yahoo mapping for every other ticker already referenced by an account or a
-- holding, so existing stock/ETF positions keep pricing exactly as before (the stored ticker
-- has always been the Yahoo symbol, used verbatim). Excluded: EUR (no conversion needed),
-- Trade Republic's fake crypto ISINs (XF000…, unresolvable), and raw ISINs (Yahoo rejects them).
INSERT INTO financial_asset (symbol, type, status, yahoo_symbol)
SELECT DISTINCT UPPER(TRIM(t.ticker)), 'UNKNOWN', 'AUTO', UPPER(TRIM(t.ticker))
FROM (
    SELECT ticker FROM account_holding
    UNION
    SELECT ticker FROM account
) t
WHERE t.ticker IS NOT NULL
  AND TRIM(t.ticker) <> ''
  AND UPPER(TRIM(t.ticker)) <> 'EUR'
  AND UPPER(TRIM(t.ticker)) NOT LIKE 'XF000%'
  AND UPPER(TRIM(t.ticker)) !~ '^[A-Z]{2}[A-Z0-9]{9}[A-Z0-9]$'
  AND UPPER(TRIM(t.ticker)) NOT IN (SELECT symbol FROM financial_asset);
