-- V51: financial_asset — one row per priceable asset (crypto, stock, ETF), replacing the
-- hardcoded ticker registries (CoinGeckoPriceProvider.TICKER_TO_ID and the drifted crypto
-- skip-list in YahooFinancePriceProvider). Aggregator references are dedicated nullable
-- columns — one column per aggregator (decided 2026-07-08 over a junction table: there is
-- exactly one external ref per (asset, aggregator)). A row is priceable on the aggregators
-- whose ref column is set; `status` tracks the resolution lifecycle:
--   PENDING   discovered but not linked to any aggregator yet (awaiting auto/user resolution)
--   AUTO      linked automatically (single or market-cap-dominant search match)
--   USER      linked or corrected by the operator
--   WORTHLESS delisted coin priced at a known zero (no aggregator ref)
-- `last_eur_value`/`price_synced_at` persist the latest known price so a restart doesn't start
-- from an empty in-memory cache. See FinancialAssetService for the resolution rules.
CREATE TABLE financial_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Uppercase internal ticker as seen in holdings and imports (BTC, IWDA.AS, …).
    symbol VARCHAR(30) NOT NULL,
    name VARCHAR(120),
    -- CRYPTO | STOCK | ETF | UNKNOWN — routing hint and UI grouping, not a hard constraint.
    type VARCHAR(10) NOT NULL DEFAULT 'UNKNOWN',
    status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    isin VARCHAR(12),
    -- CoinGecko coin id (e.g. 'bitcoin', 'matic-network'), used verbatim in API calls.
    coingecko_id VARCHAR(100),
    -- Yahoo Finance symbol (e.g. 'IWDA.AS', 'MC.PA'), used verbatim in API calls.
    yahoo_symbol VARCHAR(50),
    last_eur_value NUMERIC(20, 8),
    price_synced_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_financial_asset_symbol UNIQUE (symbol)
);

-- No seed rows. The registry starts EMPTY and is built entirely from real data:
--   • existing holdings are migrated into it by V52 (one row per held ticker, PENDING/UNKNOWN);
--   • at runtime, holding write paths call FinancialAssetService.getOrCreate(symbol), and the
--     crypto import/verification flow resolves each symbol to a CoinGecko id (AUTO/USER).
-- A fresh install therefore boots with an empty registry that fills as accounts are synced —
-- no hardcoded ticker→id list lives in the schema (that map used to be
-- CoinGeckoPriceProvider.TICKER_TO_ID; it is gone, resolution is now dynamic).
