-- V54: aggregator + aggregator_session — persistent identity and API credentials for the price
-- aggregators behind PriceProviderPort (CoinGecko, Yahoo, and later CoinMarketCap). One `aggregator`
-- row per provider, keyed by PriceProviderPort.aggregatorKey(); `aggregator_session` holds the API
-- credentials used against it. Several sessions per aggregator are allowed so rate limits can be
-- spread over multiple keys.
--
-- Credentials are encrypted at rest (AES-GCM via CryptoEncryption), so api_key/api_secret store
-- base64 ciphertext (VARCHAR(500), matching the other encrypted-credential tables) and are nullable
-- (Yahoo needs no key). `enabled` pauses an aggregator or a single key without deleting the row.
--
-- App-global config — deliberately NO member_id: a price API key is instance-wide, unlike the
-- per-member bank/broker sessions (bourso_session, trade_republic_session, …). These sessions are
-- kept separate from those by design, not merged into one table (heterogeneous shapes + different
-- scope/lifecycle).
CREATE TABLE aggregator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Stable key matching PriceProviderPort.aggregatorKey() (e.g. 'coingecko', 'yahoo').
    aggregator_key VARCHAR(50) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_aggregator_key UNIQUE (aggregator_key)
);

CREATE TABLE aggregator_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregator_id BIGINT NOT NULL REFERENCES aggregator(id) ON DELETE CASCADE,
    -- Human label to tell several keys of the same aggregator apart in the admin panel.
    label VARCHAR(100),
    -- AES-GCM ciphertext (base64); nullable — Yahoo has no key. Never returned in plaintext.
    api_key VARCHAR(500),
    api_secret VARCHAR(500),
    last_sync_at TIMESTAMPTZ,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_aggregator_session_aggregator_id ON aggregator_session (aggregator_id);

-- Seed the two providers that exist today. No sessions are seeded: the operator adds API keys from
-- the admin panel. Until then CoinGecko runs on the anonymous free tier and Yahoo needs no key.
INSERT INTO aggregator (aggregator_key, display_name) VALUES
    ('coingecko', 'CoinGecko'),
    ('yahoo',     'Yahoo Finance');
